### ISSUE TITLE
HW 2 evaluation

### ISSUE THREAD

**Issue by vmarcella** [ebonnecab/ds2-1#2]
## General evaluation
Really good visualizations and nice scoring model! The joint plots are a good addition to the notebook. The second heatmap with all of the variables is pretty hard to read and I think that could be fixed by removing one half of the heatmap. I also think that  you can use more markdown to commentate what's going on, but following along the code isn't too hard in this case.

## What I really liked
Your pair plot shows some pretty interesting data given the `prognosis`, `worst concavity`, and `worst perimeter`. Without any machine learning, you could probably make some accurate predictions by hand on if someone had breast cancer using these visualizations and the necessary data.

## What I think could be improved
Your heatmap is very hard to interpret because there are way too many variables. I'd recommend either reducing the amount of variables shown or removing half of the heatmap to get more space back.

## Overall
Great work, however I can't mark it as a pass yet. I saw some comments about including data normalization and PCA, but neither of those is needed. What is needed is a confusion matrix, precision score, recall score, and f1-score which are all derived from the confusion matrix. You already have the accuracy score, so now all you need to do is use the predictions you've obtained to create the rest.

**Comment by ebonnecab** [comment]
@C3NZ Thanks for the feedback! I refactored my code so you can grade it again whenever you get a chance.
